/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stakingSystemSol from './StakingSystem.sol/index';
export { CourseManager__factory } from './CourseManager__factory';
export { YDToken__factory } from './YDToken__factory';