/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingSystemSol from './StakingSystem.sol/index';
export type { stakingSystemSol };
export type { CourseManager } from './CourseManager';
export type { YDToken } from './YDToken';
export * as factories from './factories/index';
export { CourseManager__factory } from './factories/CourseManager__factory';
export type { IAToken } from './StakingSystem.sol/IAToken';
export { IAToken__factory } from './factories/StakingSystem.sol/IAToken__factory';
export type { IPool } from './StakingSystem.sol/IPool';
export { IPool__factory } from './factories/StakingSystem.sol/IPool__factory';
export type { IPoolAddressesProvider } from './StakingSystem.sol/IPoolAddressesProvider';
export { IPoolAddressesProvider__factory } from './factories/StakingSystem.sol/IPoolAddressesProvider__factory';
export type { IPoolDataProvider } from './StakingSystem.sol/IPoolDataProvider';
export { IPoolDataProvider__factory } from './factories/StakingSystem.sol/IPoolDataProvider__factory';
export type { IQuoter } from './StakingSystem.sol/IQuoter';
export { IQuoter__factory } from './factories/StakingSystem.sol/IQuoter__factory';
export type { ISwapRouter } from './StakingSystem.sol/ISwapRouter';
export { ISwapRouter__factory } from './factories/StakingSystem.sol/ISwapRouter__factory';
export type { StakingSystem } from './StakingSystem.sol/StakingSystem';
export { StakingSystem__factory } from './factories/StakingSystem.sol/StakingSystem__factory';
export { YDToken__factory } from './factories/YDToken__factory';