/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAToken } from './IAToken';
export type { IPool } from './IPool';
export type { IPoolAddressesProvider } from './IPoolAddressesProvider';
export type { IPoolDataProvider } from './IPoolDataProvider';
export type { IQuoter } from './IQuoter';
export type { ISwapRouter } from './ISwapRouter';
export type { StakingSystem } from './StakingSystem';