/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common"
  

  export interface IPoolDataProviderInterface extends Interface {
    getFunction(nameOrSignature: "getReserveData" | "getReserveTokensAddresses"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getReserveData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReserveTokensAddresses', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getReserveData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserveTokensAddresses', data: BytesLike): Result;
  }

  

  export interface IPoolDataProvider extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPoolDataProvider;
    waitForDeployment(): Promise<this>;

    interface: IPoolDataProviderInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getReserveData: TypedContractMethod<
      [asset: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {unbacked: bigint, accruedToTreasuryScaled: bigint, totalAToken: bigint, totalStableDebt: bigint, totalVariableDebt: bigint, liquidityRate: bigint, variableBorrowRate: bigint, stableBorrowRate: bigint, averageStableBorrowRate: bigint, liquidityIndex: bigint, variableBorrowIndex: bigint, lastUpdateTimestamp: bigint }],
      'view'
    >
    

    
    getReserveTokensAddresses: TypedContractMethod<
      [asset: AddressLike, ],
      [[string, string, string] & {aTokenAddress: string, stableDebtTokenAddress: string, variableDebtTokenAddress: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getReserveData'): TypedContractMethod<
      [asset: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {unbacked: bigint, accruedToTreasuryScaled: bigint, totalAToken: bigint, totalStableDebt: bigint, totalVariableDebt: bigint, liquidityRate: bigint, variableBorrowRate: bigint, stableBorrowRate: bigint, averageStableBorrowRate: bigint, liquidityIndex: bigint, variableBorrowIndex: bigint, lastUpdateTimestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getReserveTokensAddresses'): TypedContractMethod<
      [asset: AddressLike, ],
      [[string, string, string] & {aTokenAddress: string, stableDebtTokenAddress: string, variableDebtTokenAddress: string }],
      'view'
    >;

    

    filters: {
      
    };
  }